import Head from 'next/head';
import React from 'react'
import Header from '../Header';
import styles from './Layout.module.css';

interface Props {
    LeftChild: React.ReactElement;
    text: string;
    RightChild: React.ReactElement;
    children? : JSX.Element | JSX.Element []
  }

function Layout({ text, LeftChild, RightChild , children}:Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>감정 일기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header
          text={text}
          LeftChild={
            LeftChild
          }
          RightChild={
            RightChild
          }
        />
        {children}
      </main>
    </div>
  )
}

export default Layout