import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Button from '../components/Button/index'
import Header from '../components/Header/index'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [curDate, setCurDate] = useState<Date>(new Date());

  const prevBtnClick = () => {
    console.log(new Date().toLocaleDateString())
  }
  const nextBtnClick = () => {
    console.log(new Date().toLocaleDateString())
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header 
          text={new Date().toLocaleDateString()} 
          LeftChild={<Button text='<' className='default' onClick={prevBtnClick} />} 
          RightChild={<Button text='>' className='default' onClick={nextBtnClick} />} 
        />
      </main>
    </div>
  )
}

export default Home
