import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect, useMemo, useState } from "react";
import Button from "../components/Button/index";
import Header from "../components/Header/index";
import List from "../components/List";
import styles from "../styles/Home.module.css";
import { DirayList as Props } from "../types/home";

const Home: NextPage<Props> = ({ list }) => {
  const [currentDate, setCurrentDate] = useState(new Date());

  const monthChangeHandler = useCallback((type : 'prev' | 'next')=>{
    const currentYear = currentDate.getFullYear();
    const currentMonth = currentDate.getMonth();
    const date = new Date(currentYear,  type === 'prev' ? currentMonth -1 : currentMonth + 1 ,1)
    setCurrentDate(date)
  }, [currentDate])
  
  const headerTitle = useMemo(
    () => `${currentDate.getFullYear()}년 ${currentDate.getMonth() + 1}월`,
    [currentDate]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>감정 일기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header
          text={headerTitle}
          LeftChild={
            <Button text="<" className="default" onClick={()=>monthChangeHandler('prev')} />
          }
          RightChild={
            <Button text=">" className="default" onClick={()=>monthChangeHandler('next')} />
          }
        />
        <List list={list} />
      </main>
    </div>
  );
};

export default Home;

/**
 *
 * @param context
 * @returns context.req / res / cookies
 */
export const getServerSideProps: GetServerSideProps = async (context) => {
  let list = [];
  try {
    const res = await fetch("http://localhost:3000/diary/lists");
    if (res.statusText === "OK") {
      list = await res.json();
    }
  } catch (e) {
    console.log("[error]", e);
  }
  return {
    props: {
      list,
    },
  };
};
